version: "3.8"
services:
  node-1:
    build: .
    ports:
      - "8080:8080"
    command: ["java", "-jar", "kafkaesque-1.0.0.jar", "node-1", "8080"]
  node-2:
    build: .
    ports:
      - "8081:8080"
    command: ["java", "-jar", "kafkaesque-1.0.0.jar", "node-2", "8081"]
  node-3:
    build: .
    ports:
      - "8082:8080"
    command: ["java", "-jar", "kafkaesque-1.0.0.jar", "node-3", "8082"]
  node-4:
    build: .
    ports:
      - "8083:8080"
    command: ["java", "-jar", "kafkaesque-1.0.0.jar", "node-4", "8083"]



